---

#En este Playbook se desarrolla el despliegue en Kubernetes de un Nginx

- hosts: master
  become: true

  tasks:

  - name: Abrir puerto http
    firewalld:
      service: http
      permanent: true
      state: enabled
  
  - name: Hacer un reload de firewalld
    systemd:
      name: firewalld
      state: reloaded

  - name: Creamos el deployment
    become: yes
    command: kubectl create deployment nginx --image=nginx
  
  - name: Exponemos app por el puerto 80
    become_user: rick
    command: kubectl expose deploy nginx --port 80 --target-port 80 --type NodePort