---

#En este Playbook se desarrolla la instlación del Ingress Controller

- hosts: master
  become: true

  tasks:

  - name: Instalamos un Ingress Controller
    become: yes
    command: kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml