---

#En este Playbook se desarrolla la instalación de Docker

- hosts: all
  become: true

  tasks:

  - name: Agregar repositorio
    command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  
  - name: Instalar Docker (latest)
    package:
      name: docker-ce
      state: latest
  
  - name: Iniciar Docker
    service:
      name: docker
      state: started
      enabled: yes