---

#En este Playbook se desarrolla la instalación de Kubernetes

- hosts: all
  become: true

  tasks:

  - name: Crear el fichero kubernetes.repo
    file:
      path: /etc/yum.repos.d/kubernetes.repo
      state: touch

  - name: Agregar lineas a kubernetes.repo
    lineinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      line: "{{item}}"
    loop:
      - '[kubernetes]'
      - 'name=Kubernetes'
      - 'baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
      - 'enabled=1'
      - 'gpgcheck=1'
      - 'repo_gpgcheck=1'
      - 'gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'

  - name: Instalar kubelet, kubeadm, kubectl
    dnf:
      name: "{{item}}"
      state: present
    loop:
      - kubelet
      - kubeadm
      - kubectl

  - name: Iniciar Kubernetes (kubelet)
    systemd:
      name: kubelet
      daemon_reload: yes
      state: started
      enabled: yes