---

#En este Playbook se desarrolla la instalación del CNI en el nodo master y se define CIDR del cluster

- hosts: master
  become: true

  tasks:

  - name: Configuramos kubeadm 
    shell: kubeadm init --pod-network-cidr 10.244.0.0/16 >> cluster_info.txt
    register: kubeadm_init_out
    args:
      chdir: /home/rick
      creates: cluster_info.txt