---

#En este Playbook se desarrolla la configuración de los nodos workers

- hosts: master
  become: yes
  gather_facts: false

  tasks:

  - name: Creamos un nuevo token para el Cluster-Join
    command: kubeadm token create --print-join-command
    register: join_command
  
  - debug:
      var: join_command
  
  - name: set join command
    set_fact:
      join_command: "{{ join_command.stdout_lines[0] }}"


- hosts: workers
  become: yes

  tasks:

  - name: Abrir puertos en FW 10250/tcp, 30000-32767/tcp
    firewalld:
      zone: public
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - 10250/tcp
      - 30000-32767/tcp
  
  - name: Hacer un reload de firewalld
    systemd:
      name: firewalld
      state: reloaded
    
  - name: Agregamos workers al cluster
    become: yes
    shell: "{{ hostvars['azunir-vm-k8s-master-nfs'].join_command }} >> node_joined.txt"
    args:
      chdir: /home/rick
      creates: node_joined.txt