---

  # Este playbook contiene un módulo tipo "Raw" que permite la instalación de python en los nodos gestionados

- hosts: all
  become: yes

  tasks:

- name: Instalar Python3
  raw: dnf install python36 -y