---

#En este Playbook se desarrolla la instalación de la SDN en Azure

- hosts: all
  become: true

  tasks:

  - name: Abrir puertos en FW 8285/udp y 8472/udp
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - 8285/udp
      - 8472/udp
  
  - name: Hacer un reload de firewalld
    systemd:
      name: firewalld
      state: reloaded

- hosts: master
  become: true

  tasks:

  - name: Aplicar fichero SDN
    become: yes
    become_user: rick
    command: kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml